#!/usr/bin/bash

# install bundler and bundle install
# running as root user

set -e

umask 022

# put 'gem' in the PATH
# (this wasn't yet part of .bashrc when .bashrc last ran)
. /home/ubuntu/provisioned_env.sh

cd /home/ubuntu/contra

gem install bundler
bundle config set --local deployment true
bundle config set --local without 'development test'
bundle install --retry 3

# experimental: try precompiling assets. We may get a fresh git pull
# later, but I think it's make(1)-like and will recycle this work
# sudo -u ubuntu -g rails -i bash -c 'cd /home/ubuntu/contra && id && RAILS_ENV=production BUILDING_PACKER_IMAGE=yep EXECJS_RUNTIME=Node bundle exec rake assets:precompile'
