#!/usr/bin/bash

# configure rails

POSTGRES_PASSWORD=$1

set -e

if [ -z "$POSTGRES_PASSWORD" ]
then
  1>&2 echo "expected required argument POSTGRES_PASSWORD"
  exit 1
fi

cd ~/contra

sed -i "s/CONTRADB_PRODUCTION_PASSWORD_GOES_HERE/$POSTGRES_PASSWORD/g" config/database.yml

echo "export RAILS_ENV=production" > ~/provisioned_env.d/rails
export RAILS_ENV=production

echo "SO FAR SO GOOD"
>&2 echo "SO FAR SO GOOD"
bin/rails db:create
>&2 echo "DONE"
echo DONE

# TODO find some other way to get this file here...
# psql contraprod < /tmp/contraprod.sql
# currently thinking: terraform ssh provisioner since I don't want to build a new image every day (so not packer)
# and not cloud-init, since it can't handle the file size
# rm /tmp/contraprod.sql

# TODO start the servers...
