#!/bin/bash

set -e
# set -x

if [ -z "$CONTRADB_IP" ]
then
  echo "\$CONTRADB_IP is not set"
  exit 1
fi

if [ -z "$HOME" ]
then
  echo "\$HOME is not set"
  exit 1
fi

backup_sql="contradb-$(date -u +%Y-%m-%d).sql"
backup_dir="$HOME/priv/contradb"
if [[ -r "$backup_dir/$backup_sql" && -s "$backup_dir/$backup_sql" ]]
then
  echo "$backup-dir/$backup_sql already exists"
else
  ssh "rails@$CONTRADB_IP" bin/contradb-backup
  scp "rails@$CONTRADB_IP:$backup_sql" "$backup_dir"
fi

rsync -r --exclude letsencrypt/live/ "root@$CONTRADB_IP:/etc/letsencrypt" "$backup_dir"

exit 0
