#!/bin/bash

# Prototype provision and deploy script
# Note that there is a successful deploy script on the digital ocean droplet, but 
# it doesn't deal with all side-trips like updating rbenv.

# Run this from the project root directory...

# update rbenv
cd /home/rails/.rbenv/plugins/ruby-build && git pull && cd -
rbenv install --skip-existing `cat .ruby-version`
gem install bundler
# side trip to install yarn from ppa
# side trip to install node via nvm
# try to precompile, and fail, with a miniracer error. 
EXECJS_RUNTIME=Node RAILS_ENV=production bundle exec rake assets:precompile
