apiVersion: v1
kind: Service
metadata:
  name: puma-service
  labels:
    app: contradb-puma
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: contradb-puma