require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ChoreographersController, type: :controller do

  before (:each) {request.env["HTTP_REFERER"] = "whatever"}

  let(:valid_attributes) {{name: "Cary Ravitz",
                           publish: 'never',
                           website: "http://www.nytimes.com"}}

  let(:invalid_attributes) {{name: "Li"}}

  let(:admin) {FactoryGirl.create(:user, admin: true)}
  let(:user) {FactoryGirl.create(:user, admin: false)}

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChoreographersController. Be sure to keep this updated too.
  let(:valid_session) { {} }


  describe "GET #index" do
    it "assigns all choreographers as @choreographers" do
      choreographer = Choreographer.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:choreographers)).to eq([choreographer])
    end
  end

  describe "GET #show" do
    it "assigns the requested choreographer as @choreographer" do
      choreographer = Choreographer.create! valid_attributes
      get :show, params: {:id => choreographer.to_param}, session: valid_session
      expect(assigns(:choreographer)).to eq(choreographer)
    end
  end

  describe "GET #new" do
    it "assigns a new choreographer as @choreographer" do
      @request.env["devise.mapping"] = Devise.mappings[:user]
      sign_in admin
      get :new, params: {}, session: valid_session
      expect(assigns(:choreographer)).to be_a_new(Choreographer)
    end

    it "doesn't work as a non-admin user" do
      @request.env["devise.mapping"] = Devise.mappings[:user]
      sign_in user
      get :new, params: {}, session: valid_session
      expect(assigns(:choreographer)).to be(nil)
    end
  end

  describe "GET #edit" do
    it "assigns the requested choreographer as @choreographer" do
      choreographer = Choreographer.create! valid_attributes
      @request.env["devise.mapping"] = Devise.mappings[:user]
      sign_in admin
      get :edit, params: {:id => choreographer.to_param}, session: valid_session
      expect(assigns(:choreographer)).to eq(choreographer)
    end

    it "doesn't work as a non-admin user" do
      choreographer = Choreographer.create! valid_attributes
      @request.env["devise.mapping"] = Devise.mappings[:user]
      sign_in user
      get :edit, params: {:id => choreographer.to_param}, session: valid_session
      expect(assigns(:choreographer)).to be(nil)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Choreographer" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        sign_in admin
        expect {
          post :create, params: {:choreographer => valid_attributes}, session: valid_session
        }.to change(Choreographer, :count).by(1)
      end

      it "does not work as a non-admin" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        sign_in user
        expect {
          post :create, params: {:choreographer => valid_attributes}, session: valid_session
        }.to change(Choreographer, :count).by(0)
      end

      it "assigns a newly created choreographer as @choreographer" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        sign_in admin
        post :create, params: {:choreographer => valid_attributes}, session: valid_session
        expect(assigns(:choreographer)).to be_a(Choreographer)
        expect(assigns(:choreographer)).to be_persisted
      end

      it "redirects to the created choreographer" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        sign_in admin
        post :create, params: {:choreographer => valid_attributes}, session: valid_session
        expect(response).to redirect_to(Choreographer.last)
      end

      it "saves form values" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        sign_in admin
        post :create, params: {:choreographer => valid_attributes}, session: valid_session
        choreographer = assigns(:choreographer).reload
        expect(choreographer.name).to eq(valid_attributes[:name])
        expect(choreographer.publish.to_s).to eq(valid_attributes[:publish])
        expect(choreographer.website).to eq(valid_attributes[:website])
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved choreographer as @choreographer" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        sign_in admin
        post :create, params: {:choreographer => invalid_attributes}, session: valid_session
        expect(assigns(:choreographer)).to be_a_new(Choreographer)
      end

      it "re-renders the 'new' template" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        sign_in admin
        post :create, params: {:choreographer => invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { publish: :always,
          website: "http://www.yahoo.com",
          name: "Bob Green"
        }
      }

      it "updates the requested choreographer" do
        choreographer = Choreographer.create! valid_attributes
        expect(choreographer.publish_always?).to be(false)
        expect(choreographer.publish_sometimes?).to be(false)
        expect(choreographer.publish_never?).to be(true)
        @request.env["devise.mapping"] = Devise.mappings[:user]
        sign_in admin
        put :update, params: {:id => choreographer.to_param, :choreographer => new_attributes}, session: valid_session
        choreographer.reload
        expect(choreographer.publish_always?).to be(true)
        expect(choreographer.publish_sometimes?).to be(false)
        expect(choreographer.publish_never?).to be(false)
        expect(choreographer.website).to eq(new_attributes[:website])
        expect(choreographer.name).to eq(new_attributes[:name])
      end

      it "assigns the requested choreographer as @choreographer" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        sign_in admin
        choreographer = Choreographer.create! valid_attributes
        put :update, params: {:id => choreographer.to_param, :choreographer => valid_attributes}, session: valid_session
        expect(assigns(:choreographer)).to eq(choreographer)
      end

      it "redirects to the choreographer" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        sign_in admin
        choreographer = Choreographer.create! valid_attributes
        put :update, params: {:id => choreographer.to_param, :choreographer => valid_attributes}, session: valid_session
        expect(response).to redirect_to(choreographer)
      end
    end

    context "with invalid params" do
      it "assigns the choreographer as @choreographer" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        sign_in admin
        choreographer = Choreographer.create! valid_attributes
        put :update, params: {:id => choreographer.to_param, :choreographer => invalid_attributes}, session: valid_session
        expect(assigns(:choreographer)).to eq(choreographer)
      end

      it "re-renders the 'edit' template" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        sign_in admin
        choreographer = Choreographer.create! valid_attributes
        put :update, params: {:id => choreographer.to_param, :choreographer => invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested choreographer" do
      @request.env["devise.mapping"] = Devise.mappings[:user]
      sign_in admin
      choreographer = Choreographer.create! valid_attributes
      expect {
        delete :destroy, params: {:id => choreographer.to_param}, session: valid_session
      }.to change(Choreographer, :count).by(-1)
    end

    it "redirects to the choreographers list" do
      @request.env["devise.mapping"] = Devise.mappings[:user]
      sign_in admin
      choreographer = Choreographer.create! valid_attributes
      delete :destroy, params: {:id => choreographer.to_param}, session: valid_session
      expect(response).to redirect_to(choreographers_url)
    end
  end

end
