name: CI RSpec Tests

on: [push]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.6
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_DB: contratest
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: "balance+swing"

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.6

      - name: Install PostgreSQL
        run: sudo apt-get -yqq install libpq-dev

      - name: Run bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run yarn install
        run: yarn install
      - name: Setup Database
        env:
          RAILS_ENV: test
          CONTRADB_DATABASE_HOST: localhost
        run: bin/rails db:create db:schema:load

      - name: Build and test with rspec
        env:
          RAILS_ENV: test
          CONTRADB_DATABASE_HOST: localhost
        run: bundle exec rspec spec
