name: CI RSpec Tests

on: [push]

jobs:
  build:
    name: continuous integration
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.6
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_DB: contratest
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: "balance+swing"

    steps:
      - uses: actions/checkout@v1

      - name: yarn install
        run: yarn install

      - name: jest tests
        run: yarn test

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.6

      - name: install postgres client
        run: sudo apt-get -yqq install libpq-dev

      - name: cache gems
        uses: actions/cache@v2
        id: cache-gems
        # env:
        #   cache-name: cache-gems
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
          # npm cache files are stored in `~/.npm` on Linux/macOS
          # path: ~/.npm
          # key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          # restore-keys: |
          #   ${{ runner.os }}-build-${{ env.cache-name }}-
          #   ${{ runner.os }}-build-
          #   ${{ runner.os }}-

      - name: bundle install
        if: steps.cache-gems.outputs.cache-hit != 'true'
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: initialize database
        env:
          RAILS_ENV: test
          CONTRADB_DATABASE_HOST: localhost
        run: bin/rails db:create db:schema:load

      - name: rspec tests
        env:
          RAILS_ENV: test
          CONTRADB_DATABASE_HOST: localhost
        run: bundle exec rspec spec
